# Generated by Django 4.1.3 on 2022-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_page_1_cross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_of_r', models.CharField(max_length=20)),
                ('value1', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
