# Generated by Django 4.1.3 on 2022-11-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0002_main_page_1_cross_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_page_1_cross',
            new_name='Mainpage1cross',
        ),
    ]
