# Generated by Django 4.1.3 on 2022-11-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0007_remove_mainpage1cross_created_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mainpage1cross',
            new_name='Mainpage1_cross',
        ),
    ]
