# Generated by Django 4.1.3 on 2022-11-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0009_about_us_contact_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('text1_1', models.TextField()),
                ('text1_2', models.TextField()),
                ('text2_1', models.TextField()),
                ('text2_2', models.TextField()),
                ('image_down1', models.ImageField(upload_to='')),
                ('image_down2', models.ImageField(upload_to='')),
                ('image_down3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Guides',
        ),
    ]
