# Generated by Django 4.1.3 on 2022-11-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0010_products_delete_guides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='image_down1',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='image_down2',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='image_down3',
        ),
        migrations.AddField(
            model_name='about_us',
            name='text1_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='text2_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='text3_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='text3_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='text3_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='text1_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='text1_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='text2_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='text2_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
