# Generated by Django 4.1.3 on 2022-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0011_remove_about_us_image_down1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='title',
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga2',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga3',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga4',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga5',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga6',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga7',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga8',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='imga9',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='txta9',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
