# Generated by Django 4.1.3 on 2022-11-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0012_remove_mainpage1_cross_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage1_cross',
            old_name='imga',
            new_name='imga1',
        ),
    ]
