# Generated by Django 4.1.3 on 2022-11-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0013_rename_imga_mainpage1_cross_imga1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='imga4',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='imga5',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='imga6',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='imga7',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='imga8',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='imga9',
        ),
    ]
