# Generated by Django 4.1.3 on 2022-11-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0014_remove_mainpage1_cross_imga4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='txta7',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='txta8',
        ),
        migrations.RemoveField(
            model_name='mainpage1_cross',
            name='txta9',
        ),
    ]
