# Generated by Django 4.1.3 on 2022-11-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0015_remove_mainpage1_cross_txta7_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_down1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_down2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_down3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='text1_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='text1_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='text2_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='text2_2',
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='prc1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='prc2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='prc3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='imge1',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='imge2',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='imge3',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='txte1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='txte2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='txte3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='txte4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='txte5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='txte6',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
