# Generated by Django 4.1.3 on 2022-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosy', '0016_remove_products_image1_remove_products_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage1_cross',
            name='titlq1_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='titlq2_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainpage1_cross',
            name='titlq2_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
